Incapsulate configs
cloudposse/github-action-atmos-terraform-plan pull request #48
Opened 2023-12-04 20:37 UTC by goruha

## what

* Incapsulate configs

2023-12-06 21:13 UTC, milldr requested changes
example needs to be updated with the major change, and PR description should describe what and why we're submitting a major change

https://github.com/cloudposse/github-action-atmos-terraform-plan/blob/main/README.yaml#L56-L92

2023-12-12 00:57 UTC, goruha commented
@milldr ReadME updated

2023-12-15 21:27 UTC, Benbentwo approved these changes

2023-12-15 21:29 UTC, milldr submitted a review, later dismissed

2023-12-15 21:35 UTC, osterman approved these changes

2023-12-15 21:40 UTC, merged